-- begin TRANSPORTMANAGEMENT_CLIENT
create unique index IDX_TRANSPORTMANAGEMENT_CLIENT_UK_CODE_CLIENT on TRANSPORTMANAGEMENT_CLIENT (CODE_CLIENT) where DELETE_TS is null ^
-- end TRANSPORTMANAGEMENT_CLIENT
-- begin TRANSPORTMANAGEMENT_GATE
create unique index IDX_TRANSPORTMANAGEMENT_GATE_UK_NUMBER_GATE on TRANSPORTMANAGEMENT_GATE (NUMBER_GATE) where DELETE_TS is null ^
-- end TRANSPORTMANAGEMENT_GATE
-- begin PROVIDER_CLIENT_LINK
alter table PROVIDER_CLIENT_LINK add constraint FK_PROCLI_ON_PLANIN foreign key (CLIENT_ID) references TRANSPORTMANAGEMENT_PLANIN(ID)^
alter table PROVIDER_CLIENT_LINK add constraint FK_PROCLI_ON_CLIENT foreign key (PROVIDER_ID) references TRANSPORTMANAGEMENT_CLIENT(ID)^
-- end PROVIDER_CLIENT_LINK
