-- begin TRANSPORTMANAGEMENT_CLIENT
create unique index IDX_TRANSPORTMANAGEMENT_CLIENT_UK_CODE_CLIENT on TRANSPORTMANAGEMENT_CLIENT (CODE_CLIENT) where DELETE_TS is null ^
-- end TRANSPORTMANAGEMENT_CLIENT
-- begin TRANSPORTMANAGEMENT_GATE
create unique index IDX_TRANSPORTMANAGEMENT_GATE_UK_NUMBER_GATE on TRANSPORTMANAGEMENT_GATE (NUMBER_GATE) where DELETE_TS is null ^
-- end TRANSPORTMANAGEMENT_GATE
